language: java
install: true
jdk: oraclejdk8

env:
  matrix:
  - TERM=dumb

services:
  - docker

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update -qq
  - sudo apt-get install oracle-java8-installer

script:
  - if [ "$TRAVIS_BRANCH" == "master" ];
    then ./gradlew clean javadoc sonarqube jacocoTestReport jacocoRootMergeReport -S -Dsonar.login=${SONAR_TOKEN};
    else ./gradlew clean build jacocoTestReport jacocoRootMergeReport -S;
    fi


after_success:
  - ./gradlew coveralls
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    ./gradlew :documentation:asciidoctor;
    cd documentation/build/asciidoc/html5/;
    mkdir javadoc;
    mkdir javadoc/client;
    cp -a ../../../../platform/dolphin-platform-client/build/docs/javadoc/. javadoc/client;
    mkdir javadoc/client-jfx;
    cp -a ../../../../platform/dolphin-platform-client-javafx/build/docs/javadoc/. javadoc/client-jfx;
    mkdir javadoc/core;
    cp -a ../../../../platform/dolphin-platform-core/build/docs/javadoc/. javadoc/core;
    mkdir javadoc/server;
    cp -a ../../../../platform/dolphin-platform-server/build/docs/javadoc/. javadoc/server;
    mkdir javadoc/server-jee;
    cp -a ../../../../platform/dolphin-platform-server-javaee/build/docs/javadoc/. javadoc/server-jee;
    mkdir javadoc/server-spring;
    cp -a ../../../../platform/dolphin-platform-server-javaee/build/docs/javadoc/. javadoc/server-spring;
    git init;
    git config user.name "${GH_USER_NAME}";
    git config user.email "{GH_USER_EMAIL}";
    git add . ; git commit -m "Deploy to GitHub Pages";
    git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1;
    fi
