language: java
sudo: false
script: mvn clean verify
jdk: oraclejdk8
after_success:
      - zip -r release . -i java-*/target/*.jar -i release/readme.txt
      - mvn clean test jacoco:report coveralls:report
deploy:
  provider: releases
    api_key: "$github_api_token_upload_release"
  file: 'release.zip'
  skip_cleanup: true
  on:
    tags